name: ci
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  MAIN_ZOWE_VERSION: zowe-v2-lts

jobs:
  build-and-deploy-x64:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        zowe: [zowe-v1-lts, zowe-v2-lts]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: awharn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id:   build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          build-args: |
            ZOWE_VERSION=${{ matrix.zowe }}
          tags: |
            awharn/jenkins-nvm-zowe-cli:${{ matrix.zowe }}
            ghcr.io/awharn-docker/jenkins-nvm-zowe-cli:${{ matrix.zowe }}
            ${{ matrix.zowe == env.MAIN_ZOWE_VERSION && 'awharn/jenkins-nvm-zowe-cli:latest' || '' }}
            ${{ matrix.zowe == env.MAIN_ZOWE_VERSION && 'ghcr.io/awharn-docker/jenkins-nvm-zowe-cli:latest' || '' }}
      
      - name: Image Digest
        run:  echo ${{ steps.build.outputs.digest }}

  build-and-deploy-arm:
    runs-on: fastarm
    strategy:
      fail-fast: false
      matrix:
        zowe: [zowe-v1-lts, zowe-v2-lts]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: awharn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id:   build
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile-arm64
          platforms: linux/arm64
          build-args: |
            ZOWE_VERSION=${{ matrix.zowe }}
          tags: |
            awharn/jenkins-nvm-zowe-cli-arm:${{ matrix.zowe }}
            ghcr.io/awharn-docker/jenkins-nvm-zowe-cli-arm:${{ matrix.zowe }}
            ${{ matrix.zowe == env.MAIN_ZOWE_VERSION && 'awharn/jenkins-nvm-zowe-cli-arm:latest' || '' }}
            ${{ matrix.zowe == env.MAIN_ZOWE_VERSION && 'ghcr.io/awharn-docker/jenkins-nvm-zowe-cli-arm:latest' || '' }}
      
      - name: Image Digest
        run:  echo ${{ steps.build.outputs.digest }}

  update-downstream:
    runs-on: ubuntu-20.04
    needs: 
      - build-and-deploy-x64
      - build-and-deploy-arm
    steps:
      - name: Update Downstream
        uses: benc-uk/workflow-dispatch@v1
        with: 
          ref:      refs/heads/master
          workflow: ci
          repo:     awharn-docker/jenkins-nvm-zowe-cli-extended
          token:    ${{ secrets.PAT }}