name: ci
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build-and-deploy-v1:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: awharn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id:   build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          build-args: |
            ZOWE_VERSION=zowe-v1-lts
          tags: |
            awharn/jenkins-nvm-zowe-cli:zowe-v1-lts
            ghcr.io/awharn-docker/jenkins-nvm-zowe-cli:zowe-v1-lts
      
      - name: Image Digest
        run:  echo ${{ steps.build.outputs.digest }}

  build-and-deploy-v2:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: awharn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id:   build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          build-args: |
            ZOWE_VERSION=zowe-v2-lts
          tags: |
            awharn/jenkins-nvm-zowe-cli:latest
            awharn/jenkins-nvm-zowe-cli:zowe-v2-lts
            ghcr.io/awharn-docker/jenkins-nvm-zowe-cli:latest
            ghcr.io/awharn-docker/jenkins-nvm-zowe-cli:zowe-v2-lts
      
      - name: Image Digest
        run:  echo ${{ steps.build.outputs.digest }}

  build-and-deploy-v1-arm:
    runs-on: r4s
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: awharn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id:   build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm64
          build-args: |
            ZOWE_VERSION=zowe-v1-lts
          tags: |
            awharn/jenkins-nvm-zowe-cli:zowe-v1-lts
            ghcr.io/awharn-docker/jenkins-nvm-zowe-cli:zowe-v1-lts
      
      - name: Image Digest
        run:  echo ${{ steps.build.outputs.digest }}

  build-and-deploy-v2-arm:
    runs-on: r4s
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: awharn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id:   build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm64
          build-args: |
            ZOWE_VERSION=zowe-v2-lts
          tags: |
            awharn/jenkins-nvm-zowe-cli:latest
            awharn/jenkins-nvm-zowe-cli:zowe-v2-lts
            ghcr.io/awharn-docker/jenkins-nvm-zowe-cli:latest
            ghcr.io/awharn-docker/jenkins-nvm-zowe-cli:zowe-v2-lts
      
      - name: Image Digest
        run:  echo ${{ steps.build.outputs.digest }}
  
  update-downstream:
    runs-on: ubuntu-20.04
    needs: 
      - build-and-deploy-v1
      - build-and-deploy-v2
      - build-and-deploy-v1-arm
      - build-and-deploy-v2-arm
    steps:
      - name: Update Downstream
        uses: benc-uk/workflow-dispatch@v1
        with: 
          ref:      refs/heads/master
          workflow: ci
          repo:     awharn-docker/jenkins-nvm-zowe-cli-extended
          token:    ${{ secrets.PAT }}